Processor = require "#{process.cwd()}/dist/lib/processor"

# Log each of the summaries generated by generateSummary()
processResults = (results) ->
  for result in results
    console.log result

processor = new Processor()

# If we have a file argument, process file. Otherwise, process from stdin
if process.argv[2]
  lineReader = require('readline').createInterface(input: require('fs').createReadStream(process.argv[2]))
  lineReader.on 'line', (line) ->
    processor.processLine line
  lineReader.on 'close', () ->
    results = processor.generateSummary true
    processResults results
else
  process.stdin.pipe(require('split')()).on 'data', (line) ->
    processor.processLine line
  process.stdin.on 'end', () ->
    results = processor.generateSummary true
    processResults results